### ISSUE TITLE
onnxruntime::Model::Model Unknown model file format version.

### ISSUE THREAD

**Issue by omar-Fouad** [PINTO0309/facemesh_onnx_tensorrt#1]
error
read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from yolov4_headdetection_480x640_post.onnx failed:D:\3\s\onnxruntime\core\graph\model.cc:110 onnxruntime::Model::Model Unknown model file format version.

**Comment by PINTO0309** [comment]
Unknown model file format version.
