### ISSUE TITLE
Error with pre-trained models 

### ISSUE THREAD

**Issue by romain87400** [PINTO0309/facemesh_onnx_tensorrt#2]
Hi Pinto, i would like to test your programme, but i think i have an error with pre-trained models because i am not rebuilding ther on my plateform. 
I work with a JetsonNX with jetpack 4.4 (i can use 4.6 i that needed), with cuda 10.2, cudnn 8.0, onnx==1.11.0, onnxgraphsurgeon==0.3.9, onnx-tensorrt==7.2.2.3.0, onnxruntime==1.8.0
 
My error is at yolov4_headdetection_480x640_post.onnx:
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from yolov4_headdetection_480x640_post.onnx failed:/mnt/vss/_work/1/s/onnxruntime/core/graph/model.cc:111 onnxruntime::Model::Model(onnx::ModelProto&&, const PathString&, const IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&) Unknown model file format version.
```
When i change my model by yolov4 headdetection 480x640.onnx, i have an error on the next model face_mesh_Nx3x192x192 _post.onnx :
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from face_mesh_Nx3x192x192_post.onnx failed:/mnt/vss/_work/1/s/onnxruntime/core/graph/model.cc:111 onnxruntime::Model::Model(onnx::ModelProto&&, const PathString&, const IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&) Unknown model file format version.
```
If i'm understand well, i must convert my model to post format model, but i don't really understand how i can do that. 
I read the "facemesh_postprocess.py", but i'm don't understand how i can use it. 

Is it possible for you, to explain how i can obtain these post models converted on my platform?
Or what version of onnxruntime i must have ?

Thank you for your answer :)

**Comment by PINTO0309** [comment]
```bash
git clone -b v1.12.1 https://github.com/microsoft/onnxruntime.git \
&& cd onnxruntime

./build.sh \
--config Release \
--cudnn_home /usr/lib/x86_64-linux-gnu/ \      #<-------------------- change your environment
--cuda_home /usr/local/cuda \      #<-------------------- change your environment
--use_tensorrt \
--use_cuda \
--tensorrt_home /usr/src/tensorrt/ \      #<-------------------- change your environment
--enable_pybind \
--build_shared_lib \
--build_wheel \
--parallel $(nproc) \
--skip_tests

find . -name "*.whl"
./build/Linux/Release/dist/onnxruntime_gpu-1.12.1-cp38-cp38-linux_x86_64.whl

pip uninstall onnxruntime onnxruntime-gpu
pip install ./build/Linux/Release/dist/onnxruntime_gpu-1.12.1-cp38-cp38-linux_x86_64.whl
```

**Comment by romain87400** [comment]
Hi Pinto, currently with jetson pack 4.4 we have TensorRT 7.1.3, and onnx_tensorrt does not compile with this version (7.1 yes but not 7.1.3)
If I understood your post, I need to have tensorRT 8.4, but in this case I should use a new jetpack SDK (maybe 5.0.2 or other).
it's easier to have the latest version of cudnn and cuda compatible.
I will test your code when I will change my SDK.
Thank you for your help and i appreciate your wonderful works :), have a nice day.
